version: '3.9'

services:
  app:
    container_name: block_app
    image: block_app
    restart: unless-stopped
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${PWD}/:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - block_net

networks:
  block_net:
    driver: bridge