version: '3.9'

services:
  redis:
    container_name: block_redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --port 6379 --loglevel warning
    env_file:
      - ${PWD}/.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - block_net

networks:
  block_net:
    driver: bridge
